version: '3.8'

services:
  rust_dev:
    container_name: rust_develop
    build:
      context: .
      dockerfile: Dockerfile
      target: rust_dev
    image: rust-develop-img
    ports:
      - "5002:8080"               # Порт для веб-интерфейса приложения
    volumes:
      - ./app:/home/rustuser/app  # Монтирование исходного кода приложения
      - ./shared_folder:/rust/shared_folder  # Общая папка для обмена файлами между хостом и контейнером
    environment:
      - RUST_ENV=development
    networks:
      - app_network
    tty: true  # Позволяет держать контейнер запущенным с интерактивным терминалом

networks:
  app_network:
    driver: bridge
